//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class sport_shoes
    {
        public int sport_shoes_id { get; set; }
        public string available_in_shop { get; set; }
        public string shoes_model { get; set; }
        public Nullable<decimal> shoes_price { get; set; }
        public string currency { get; set; }
        public Nullable<int> shoes_size { get; set; }
        public string shoes_color { get; set; }
        public string shoes_brand { get; set; }
    
        public virtual shop_info shop_info { get; set; }
    }
}
