//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportShopEntities : DbContext
    {
        public SportShopEntities()
            : base("name=SportShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<boxing_gloves> boxing_gloves { get; set; }
        public virtual DbSet<shop_info> shop_info { get; set; }
        public virtual DbSet<sport_shoes> sport_shoes { get; set; }
        public virtual DbSet<supplement> supplement { get; set; }
    }
}
