//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplement
    {
        public int supplement_id { get; set; }
        public string available_in_shop { get; set; }
        public string type { get; set; }
        public string purpose { get; set; }
        public string supplement_brand { get; set; }
        public string supplement_name { get; set; }
        public Nullable<decimal> supplement_price { get; set; }
        public string currency { get; set; }
        public Nullable<int> supplement_rating { get; set; }
        public string taste { get; set; }
        public Nullable<decimal> packing { get; set; }
        public string measurement_unit { get; set; }
        public Nullable<int> servings { get; set; }
    
        public virtual shop_info shop_info { get; set; }
    }
}
